version: "3.5"
services:
    lect-webserver:
      image: nginx:alpine
      container_name: lect-webserver
      working_dir: /application
      volumes:
          - ../:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8081:80"
      depends_on: 
        - lect-php-fpm
      networks:
        - lectnet

    lect-php-fpm:
      build: ./php
      environment:
        PHP_IDE_CONFIG: "serverName=LECTION"
      container_name: lect-php-fpm
      working_dir: /application
      volumes:
        - ../:/application
        - ./php/www2.conf:/usr/local/etc/php-fpm.d/www2.conf
        - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      networks:
        - lectnet

networks:
  lectnet:
    name: lectnet
